### ISSUE TITLE
Autocomplete doesn't work on wordpress

### ISSUE THREAD

**Issue by pradpnayak** [TechToThePeople/publicautocomplete#40] opened 2022-05-31 12:32 UTC
When you have an event rendered using shortcode from WordPress content, the current_employer field is not converted to auto-complete.

**Comment by twomice** [comment] 2022-05-31 15:48
Thanks Pradeep. Can you tell me please:

WP version
CiviCRM version
Extension version
WP theme name and version

Also, can you check the browser's Developer Tools and tell whether the extension's main JS file (public.autocomplete-4.5.js) is being loaded?

**Comment by jaapjansma** [comment] 2022-11-09 16:01
You also need to give the Access AJAX api to anonymous users.

**Comment by twomice** [comment] 2023-06-20 14:51
@pradpnayak This issue seems to be the same one reported in #45 , which is fixed in #47, to be released within 24 hours under v1.6.4. Could you try that version and let me know if it resolves your issue?

**Comment by twomice** [comment] 2023-06-20 15:38
I've tested and confirmed this, under WordPress, CiviCRM 5.62.1:

* Under extension v1.6.3, Current Employer field **does not** respond with autocomplete behavior when not logged in
* Under extension v1.6.4, Current Employer field **does** respond with autocomplete behavior when not logged in

Closing as fixed. @pradpnayak , thank you for the report. Please re-open if yoru trouble persists under v1.6.4 or later.

**Closed as completed by twomice** 2023-06-20 15:38 UTC
