### ISSUE TITLE
Autocomplete no longer working; error console shows 404 and header mismatch

### ISSUE THREAD

**Issue by LMKWeb** [TechToThePeople/publicautocomplete#18] opened 2020-10-31 03:02 UTC
I just noticed this evening that the public autocomplete installed on our website is no longer working. I can't say when it stopped, but this is the error that pulls up in the error console:

The resource from “[site URL]//[absolute path to file]/extensions/publicautocomplete/js/public.autocomplete-4.5.js?r=iM75r” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
JQMIGRATE: Migrate is installed, version 1.4.1 jquery-migrate.min.js:2:552
Loading failed for the <script> with source “[site URL]//[absolute path to file]/extensions/publicautocomplete/js/public.autocomplete-4.5.js?r=iM75r”.

It seems like the file path is incorrect and throwing a 404, but I don't know if that's triggering the nosniff block or if we need to add some rules to .htaccess to allow it to work. Where is the extension pulling the file path from? The URL shows the public address, followed by a double slash, followed by the absolute path, hence the 404.

I'm not a developer, so I'm not certain what next steps I should take to troubleshoot. Appreciate any direction.

We're running CiviCRM 5.28.2 on Joomla 3.9.22.

**Comment by twomice** [comment] 2020-11-01 22:56
Since presumably this is a public-facing form, would you mind sharing the URL ? That would at least allow us to see the bad behavior in action and possibly make some preliminary diagnosis. If you're not comfortable sharing that here, you could share it with us privately (and securely) via the Secure Message form at https://joineryhq.com/message Thanks @LMKWeb

**Comment by LMKWeb** [comment] 2020-11-01 23:39
Sure thing. Here's the address: [https://www.usfashionindustry.com/register](https://www.usfashionindustry.com/register)

**Comment by twomice** [comment] 2020-11-01 23:59
Thanks  @LMKWeb By what I see there, this does look like a possible configuration issue in CiviCRM's "Extension resource URL" setting. Can you check that setting to ensure it's correct? (See here for some documentation on how to adjust that setting: https://docs.civicrm.org/sysadmin/en/latest/customize/extensions/#wordpress)

**Comment by LMKWeb** [comment] 2020-11-02 00:20
We're not following the suggested file location, but that's probably because the site's been running Civi for 10 years so it probably predates that suggestion. It's currently set as the absolute path under Settings: Upload Directories and Settings: Resource URLs - according to the documentation these should match. I have about a dozen other extensions installed and in use as well. Would updating this to a relative URL (from the root) cause issues with what we're running? Unfortunately I don't have a staging site, every attempt to create one has failed.

**Comment by twomice** [comment] 2020-11-02 00:31
I'm sorry to hear, it sounds like there are some configuration issues on the site (and possibly other issues, especially if cloning to a staging site has been so difficult). I have to say these issues are outside of what we can handle on this public issue queue. It sounds like you may need some specialized (most likely paid) support to resolve these issues. We're happy to help you with that, of course; please feel free to contact us via info@joineryhq.com to discuss options. I'll make sure your inquiry gets routed to me personally, so that you don't have to explain yourself all over again.

**Comment by LMKWeb** [comment] 2020-11-02 00:35
Understandable, I'll send an email shortly! Thanks

**Comment by twomice** [comment] 2020-12-30 17:27
@LMKWeb I'm closing this and adding the 'invalid' label, to indicate this is not an issue we can address in this queue (as it seems to be caused by some issues on the specific site in question, not specific to the extension itself). Please feel free to re-open with more information if you think that's not the case. Thanks!

**Closed as completed by twomice** 2020-12-30 17:27 UTC
Labels: invalid
