### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by herbdool** [TechToThePeople/publicautocomplete#35] opened 2021-10-21 15:28 UTC
Version 1.6.1 is broken in Drupal 9 because of an unnecessary `civicrm_initialize();`. Can you create a new release please? Thank you!

**Comment by twomice** [comment] 2021-10-21 15:57
Thanks for the report. We've had some changes in master since 1.6.1, and I've now tagged a new release at 1.6.2. `civicrn_initialize` is not found in this release, so perhaps that will address your issue. Please try it and report back whether we can close this issue.

**Comment by twomice** [comment] 2023-06-20 14:56
We're now at version v1.6.4 (tagged just now, should be released on c.o within 24 hours). I'll close this since I believe the issue is resolved. OP, please re-open if you're still having this problem.

**Closed as completed by twomice** 2023-06-20 14:56 UTC
