### ISSUE TITLE
Support latest CiviCRM version

### ISSUE THREAD

**Issue by morbus** [TechToThePeople/publicautocomplete#9] opened 2016-09-09 14:58 UTC
Any plans to update the extension to work with CiviCRM 4.7?

**Comment by twomice** [comment] 2016-09-09 15:22
No specific plans just yet, unless @tttp has something up his sleeve. I'd love to make it happen and don't think it would be too hard; just need to work it in between client needs.

**Comment by mrojassoto** [comment] 2016-09-09 15:31
I am on CiviCRM 4.6.20, trying this extension for the first time.  I added this to my civicrm.settings.php file:

 global $civicrm_setting;
 $civicrm_setting['eu.tttp.publicautocomplete']['params'] = array(
  'contact_type' => 'Organization',
  'return' => 'organization_name'
);
 $civicrm_setting['eu.tttp.publicautocomplete']['match_column'] = 'organization_name';

I am not filtering by any groups, or contact sub-types.  When I try to use my event sign up forms, in test mode, so I am registered as a super user, I don't see the autocomplete.  When I go to the public form, I just get a blank screen.

What am I missing?  I haven't done anything to modify 'access AJAX api' yet - because I don't know how.

**Comment by twomice** [comment] 2016-09-09 16:18
@mrojassoto Could I ask you to start a separate issue for your question? This thread is specifically to discuss "Support for CiviCRM 4.7".

(BTW, I'll be glad to help you, just want to keep the discussions well organized for the sake of everyone's sanity.  Just click that green "New Issue" button in the upper-right, and copy-paste your question there. Thanks!)

**Comment by LMKWeb** [comment] 2016-10-14 01:23
A second request here to get this extension working on 4.7. We had to upgrade due to hosting server issues, and would really love to have this functionality. Thank you!

**Comment by tttp** [comment] 2016-10-14 07:26
Hi @LMKWeb and @morbus, thanks for your interest. On my side, I won't have financial support to upgrade to 4.7 for a few months at least.

Have you tried to install manually (from git or download the file and enable)? could you detail what didn't work?

and if you had some budget to make it happen, I'm sure @twomice would be able to tackle it faster

**Comment by twomice** [comment] 2016-10-14 15:37
Ditto, I'd be grateful to hear any details on what fails in a manual install, if you have a few minutes to try it.

**Comment by axon-obriend** [comment] 2016-11-02 15:21
I just tested the extension on a site I upgraded from 4.4 and I can confirm it is working on 4.7. Anyone else tried it?

**Comment by LMKWeb** [comment] 2017-01-17 05:27
I finally got around to testing this again. Getting the following in the error console:

unreachable code after return statement             autocompleter.js:291:2

Any ideas?

**Comment by tttp** [comment] 2017-01-17 09:56
thanks for reporting

It's a notice, it shouldn't prevent any functionality, does it?

**Comment by petednz** [comment] 2017-03-20 19:11
So one and a half (?) reports that this works for 4.7. I did the following. clean-ish 4.7.15. 

installed module. 

public autocomplete field (eu.tttp.publicautocomplete)	Enabled	1.4

created event. added 'current employer' field to Profile. checked permissions for AJAX API. Visited event. just a static field for current employer. 

No errors in console.

Error log shows

/sites//files/civicrm/ext/publicautocomplete/js/public.autocomplete-4.5.js?r=gtPAW
/civicrm/event/register?reset=1&action=preview&id=8

Re-read instructions to see if i missed something obvious. Apologies if i did. Wondered if the sites//files was the issue since this was installed on a buildkit version.

Copied extension to another real 'dev' site (ie not buildkit). Enabled. Added Current Employer. Tested and bingo - it shows as an autocomplete.

So another one and a half reports that it works ;-)

**Comment by juan-silva** [comment] 2017-04-25 16:01
Having the same issue where the js file is being load with a full local path like:
Request URL:https://www.usfashionindustry.com//home/usaita/www/www/extensions/publicautocomplete-master/publicautocomplete-master/js/public.autocomplete-4.5.js?r=wRT58

the "/home/usaita/www/www/" should clearly not be included in the path. any ideas?

**Comment by MarshCastle** [comment] 2018-04-18 13:38
Hi All,
any have an estimate for how much time / money this would take to bring up to 4.7?

**Comment by themak1985** [comment] 2018-04-18 16:21
Would also like to know how much time/money to update for 4.7/5.0 compatibility.

**Comment by twomice** [comment] 2019-01-11 15:51
Renaming issue to support latest civicrm version (which is 5.9.x at time of writing).

**Comment by twomice** [comment] 2019-01-16 23:09
Hi all. I've tested this lightly on civicrm 5.10.alpha1 (buildkit) and find no outstanding issues. As far as I know, there are no issues with this extension on any version of civicrm >= 4.7, other than any open tickets on this github project.  If you're seeing bad behavior, please open a separate ticket describing your specific issue.

Closing this for now, as I believe we're compatible with the latest civicrm version.

**Closed as completed by twomice** 2019-01-16 23:09 UTC
