### ISSUE TITLE
Autocomplete doesn't work when not logged in

### ISSUE THREAD

**Issue by webmaster-cses-org-uk** [TechToThePeople/publicautocomplete#41] opened 2022-07-02 23:55 UTC
Following upgrade to CiviCRM 5.50.4 (from 5.47.3), autocomplete no longer works when the user is not logged in to the Joomla website.

The issue seems to be that the autocomplete script makes use of `civicrm_api()` (which is not recommended) rather than `civicrm_api3()` which explicitly calls API v3.

I suspect the issue is related to the fact that permissions are handled differently with API v4, although this may have nothing to do with it. In any case, changing the calls to civicrm_api3() fixed the problem.

**Comment by twomice** [comment] 2022-07-05 15:03
Thanks @webmaster-cses-org-uk I'll be looking at this next Monday.

**Comment by twomice** [comment] 2023-06-20 14:51
@webmaster-cses-org-uk  This issue seems to be the same one reported in #45 , which is fixed in #47, to be released within 24 hours under v1.6.4. Could you try that version and let me know if it resolves your issue?

**Comment by twomice** [comment] 2023-06-20 15:33
Tested and confirmed, under Joomla, CiviCRM 5.62.1:

Under extension v1.6.4, Current Employer field does respond with autocomplete behavior when not logged in.

However, worth noting, I **wasn't** actually able to reproduce bad behavior under Joomla with v1.6.3.

In any case, I'm closing this because all appears to be working properly under the latest version under Joomla. Thanks @webmaster-cses-org-uk for the report.

(As for `civicrm_api` vs `civicrm_api3`, I agree, and I'm addressing the concerns in PR #42 now.)

**Closed as completed by twomice** 2023-06-20 15:33 UTC

**Comment by webmaster-cses-org-uk** [comment] 2023-06-22 20:01
@twomice Yes seems to be all working now with 1.6.4 – thank you for looking at this.
