### ISSUE TITLE
Problem found and fixed implementing this in Drupal 8.9 with CiviCRM 5.29

### ISSUE THREAD

**Issue by JeffersonWood** [TechToThePeople/publicautocomplete#16] opened 2020-10-14 06:33 UTC
Testing this extension on our Dev site in D8 with Civi 5 and got white screen with error in the log: "Call to undefined function civicrm_initialize() in _publicautocomplete_setupJavascript() (line 83 of /mysite/files/civicrm/ext/eu.tttp.publicautocomplete/publicautocomplete.php)"

after a bit of sleuthing I just replace the command on line 83 of publicautocomplete.php:
civicrm_initialize();
 with 
\Drupal::service('civicrm')->initialize();
and all seems to work, but we'll see

**Comment by twomice** [comment] 2020-10-14 14:41
Hi @JeffersonWood Thanks for reporting this. I'm sorry to hear you're having trouble.

Can you tell exactly what steps you're taking to reach this error? For example:
1. I installed this extension [version XYZ] using [method XYZ] in CiviCRM 5.29 under Drupal 8.9
2. I configured a profile with the current_employer field, and enabled it for [a contribution page / event form / freestanding profile form / etc]
3. I visited the form as [anonymous user / admin user / etc]
4. I [took theses other steps]
5. I observed the error message stated in the OP.

Or whatever steps you take to get to the error, starting with installation of the extension.  If you can list those steps for us, it will help us to reproduce the bad behavior, which is the first step in debugging. Once we can reproduce the bad behavior, we'll be able to determine its scope (e.g., we need to learn whether it's only happening on Drupal or also on other platforms) and verify  that whatever fix we make solves that problem in all situations.

Thanks for whatever additional info you can offer.

**Comment by twomice** [comment] 2020-10-14 14:49
(BTW, since this extension is CMS-agnostic, we'll be looking for a solution that works across all CMS platforms.)

**Comment by JeffersonWood** [comment] 2020-10-14 16:33
Thanks for getting back so quick.
In my case I'm allowing authenticated users (mostly from academic institutions) to update some of their personal contact info including employer. So
1. Created a profile that included employer and selected USED FOR: Drupal User Registration, View/Edit Drupal User Account, Standalone Form or Directory, CiviEvent, Search Views.
2 Installed publicautocomplete extension version 1.6 (Drupal 8.9, Civicrm 5.29) Per instructions but without setting a filter other than 'organization' in settings.php: 
$civicrm_setting['eu.tttp.publicautocomplete']['params'] = array(
  'contact_type' => 'Organization',
  'return' => 'display_name, city'
);
3. set Drupal permissions for Authenticated users to:
access AJAX API
edit my contact
4. Login as authenticated user (non-admin) and navigate to /user/uid#/edit/profile/profileid#

If all goes well you should get a white screen or whatever error message you've configured to display a server error and a message in the Drupal log saying 'unidentified function civicrm_initialize()'

Hope that helps. 
As an aside, I'd also like to extent this functionality to another custom field "Other Institutional Affiliation" that wold display essentially the same list (though I'd kind of like to filter it differently) for individuals who are retired or have an additional university affiliation besides their primary employer.  Do you know of any examples of that sort of thing being done?

**Comment by twomice** [comment] 2020-10-22 13:56
Notes: This error appears to be caused (in D8) by the call to `civicrm_initialize()` in https://github.com/TechToThePeople/publicautocomplete/blob/master/publicautocomplete.php#L83 . But as far as I can tell, that line will only be executed in the context of `publicautocomplete_civicrm_buildForm()`, meaning that civicrm is already initialized, therefore there's no need to call `civicrm_initialize()`. We're testing now to ensure that's true.

**Comment by twomice** [comment] 2020-10-23 16:39
@JeffersonWood would you mind testing PR #17 to confirm that it addresses this issue in D8? Our testing shows that it does, and that it's also compatible with D7, WP, etc. (whereas `\Drupal::service('civicrm')->initialize();` would not be).  If you have a moment to try it, please let me know your findings. I expect we'll be merging it into the next release but would value your feedback before  doing so. Thanks!

**Comment by twomice** [comment] 2020-11-10 18:59
Just to move this forward, pending a response from OP @JeffersonWood, I've merged #17 since it fixed this issue for us in testing. I'll go ahead and close this issue, but please feel free to re-open if #17 doesn't do the trick.

**Closed as completed by twomice** 2020-11-10 18:59 UTC
