### ISSUE TITLE
Autocomplete doesn't work when not logged in

### ISSUE THREAD

**Issue by yurg** [TechToThePeople/publicautocomplete#46] opened 2023-03-01 12:07 UTC
CiviCRM 5.58.1, Wordpress 6.61

Already mentioned in  #40,  #45,  #41 however there seems no resolution so far. 
The only diff spotted in requests between auth and anonymous users is cookies sent:
- for anonymous it is only **PHPSESSID**
- authenticated user gets a bunch: 
 
` wordpress_sec_2e237274ef3ee0f58cd830e9a6250985=%7C1678826887%7CbhtVi5x3tXJs1wN1qYEalsa44p2Hw7NuLo83CephG29%7Cf6cee77ba430dcfbe1068b39ebb81a9249fdb926bbbab8b48235014bcb02ec17; wp-settings-8=libraryContent%3Dbrowse%26editor_expand%3Doff%26editor%3Dhtml%26unfold%3D0%26mfold%3Do%26ed_size%3D598; wp-settings-time-8=1677350920; wordpress_logged_in_2e237274ef3ee0f58cd830e9a6250985=%7C1678826887%7CbhtVi5x3tXJs1wN1qYEalsa44p2Hw7NuLo83CephG29%7C03387dde2f44fb971c9fb059b57ff6b1207fed6af16e03811e21791dc3e0002e; PHPSESSID=q17tqij5u4m8cbu76dp2kho8t2; wordpress_test_cookie=WP%20Cookie%20check
` 

According to comments section [here](https://civicrm.stackexchange.com/questions/43609/civicrm-access-ajax-api-not-respected-in-wordpress)  this might have or have not be related to [Authx extension](https://docs.civicrm.org/dev/en/latest/framework/authx/)   - still unclear if an additional code is needed to pass anonymous API call to civicrm and get a response.

**Comment by twomice** [comment] 2023-06-20 14:53
@yurg As you mentioned, this issue seems to be the same one reported in #45 , which is fixed in #47, to be released within 24 hours under v1.6.4. Could you try that version and let me know if it resolves your issue?

**Comment by twomice** [comment] 2023-06-20 15:16
Tested and confirmed, under WordPress, CiviCRM 5.62.1:

* Under extension v1.6.3, Current Employer field **does not** respond with autocomplete behavior when not logged in (tested under WordPress)
* Under extension **v1.6.4**, Current Employer field **does** respond with autocomplete behavior when not logged in (tested under WordPress)

Closing as fixed. @yurg , thank you for the report. Please re-open if yoru trouble persists under v1.6.4 or later.

**Closed as completed by twomice** 2023-06-20 15:16 UTC
